export const SIGNUP_ROUTES = {
  EMAIL: 'EMAIL',
  USERNAME: 'USERNAME',
  PASSWORD: 'PASSWORD',
  VERIFICATION: 'VERIFICATION',
  ROLL: 'ROLL',
};
export const FORGET_ROUTES = {
  EMAIL: 'EMAILCHECK',
  VERIFICATION: 'FORGETVERIFICATION',
  PASSWORD: 'FORGETPASSWORD',
  SUCCESSFULLY: 'SUCCESSFULLY',
};
export const MAIN_ROUTES = {
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  CHATS: 'CHATS',
};
